spring:
  application:
    name: springBootStarterBasicAuth
  main:
    allow-bean-definition-overriding: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:office;DATABASE_TO_UPPER=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create

com:
  github:
    zafkiel1312:
      basic-auth:
        create-default-admin: true
        create-default-tutor: true